// Flattens the design system's @import chain into one stylesheet.
// The split files under public/ds/css and public/ds/tokens are the source of truth;
// this exists so the browser makes one request instead of walking an import waterfall.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const DS = "public/ds";
const ENTRY = join(DS, "css/until.css");
const OUT = join(DS, "until.css");
const OUTDIR = dirname(OUT);

const seen = new Set();

function flatten(file) {
  if (seen.has(file)) return "";
  seen.add(file);
  const here = dirname(file);
  // Rewrite this file's own url()s first, while `here` is still the right base.
  const css = readFileSync(file, "utf8").replace(
    /url\((["']?)((?!data:)(?!https?:)(?!\/)[^)"']+)\1\)/g,
    (_, q, url) => `url("${relative(OUTDIR, join(here, url)).split("\\").join("/")}")`
  );
  // Then inline the imports, each resolved against this file.
  return css.replace(/@import\s+"([^"]+)"\s*;\s*/g, (_, spec) => flatten(join(here, spec)));
}

const out = "/* UNTIL Design System — generated by scripts/build-css.mjs.\n"
  + "   Do not edit: change the files under css/ and tokens/ and rebuild. */\n\n"
  + flatten(ENTRY);
writeFileSync(OUT, out);

// count real statements only - the entry file mentions @import in its own comment
const leftover = (out.replace(/\/\*[\s\S]*?\*\//g, "").match(/@import/g) || []).length;
if (leftover) { console.error(`FAIL: ${leftover} unresolved @import`); process.exit(1); }
console.log(`${OUT}  ${(out.length / 1024).toFixed(1)} KB from ${seen.size} files, 0 unresolved imports`);
